name: youtube_downloader
description: Downloads videos from youtube with ease!

publish_to: 'none'

version: 1.3.3+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0-dev.7
  youtube_explode_dart: ^1.12.4
  stream_transform: ^2.0.0
  path_provider: ^2.0.12
  path: ^1.8.0
  shared_preferences: ^2.0.7
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  win32: ^2.2.8
  auto_size_text: ^3.0.0-nullsafety.0
  collection: ^1.15.0
  json_annotation: ^4.7.0
  intl: ^0.18.0
  permission_handler: ^10.2.0
  open_file: ^3.2.1
  file_picker: ^4.0.0
  url_launcher: ^6.1.7
  id3_codec: ^1.0.3
  id3tag: ^0.2.0
  http: ^0.13.5
  ffmpeg_kit_flutter_full_gpl: ^5.1.0-LTS

dev_dependencies:
  build_runner: ^2.1.1
  json_serializable: ^6.5.4
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.11.0"

dependency_overrides:
  freezed_annotation: 0.14.2


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon-512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-icon-512.png"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/images/app-icon-512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-icon-512.png"
